add features to print "Hello, world" message on port 3000
ajstyles0524/RUST_KUP pull request #6
Opened 2021-12-10 13:36 UTC by ajstyles0524

What does this change do?
Added feature to print Hello, world on port 3000 in Rust code

Any additional information for the reviewer to start
NA

How should this be manually tested?
We need window OS in which Rust is installed. then execute this rust program

Are there any changes pending?
No

Does any team have to be notified of changes in this feature?
Yes

Definition of Done:
- [x] Is there >90% unit test code coverage?
- [x] Does this PR add new dependencies? If so, please list out the same.
      rocket = "0.5.0-rc.1"
      log = "0.4.14"
- [ ]  Will this feature require a new piece of infrastructure to be implemented?
- [x] Is there appropriate logging included?
- [x] Does the project compile ok?
- [x] Have Clippy violations been fixed?
- [x] Have Code is properly formatted?

2021-12-10 13:42 UTC, Sandeep-Knoldus approved these changes

2021-12-10 13:52 UTC, Rohit0823 approved these changes

2021-12-13 08:22 UTC, bishtpawan commented on Assignments/rocket_web/src/launch.rs
> +/// world is a handler which is used to process the request and return a response
please update documentation

2021-12-13 08:26 UTC, bishtpawan requested changes
Please update naming conventions, incorporate error handling, use proper documentation.

2021-12-13 08:26 UTC, bishtpawan commented on Assignments/rocket_web/src/launch.rs
> +/// rocket is a function which is used to startq the server
please update documentation

2021-12-13 08:26 UTC, bishtpawan commented on Assignments/rocket_web/src/launch.rs
> +    debug!("{}", "some log message");
please provide proper log messages

2021-12-13 08:26 UTC, bishtpawan commented on Assignments/rocket_web/src/launch.rs
> +pub fn launch() -> _ {
why we have _ in the return type?

2021-12-13 08:26 UTC, bishtpawan commented on Assignments/rocket_web/src/test.rs
> +mod test {
please add negative test case as well

2021-12-15 13:04 UTC, closed without merging